cache:
  pipeline: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: maven:3.6.3-jdk-8
  environment:
    #Fetches history so Sonar can assign blame.
    GIT_SHALLOW_CLONE: false

jobs:
  pull-request:
    requires: [~pr, ~commit]
    secrets:
      - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean install

  main:
    secrets:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_ENCPHRASE
      - OSSRH_USER
      - OSSRH_TOKEN
    requires: [~tag, ~release, ~commit]
    steps:
      - build: mvn -B clean install
      - publish: "screwdriver/publish_to_maven.sh"