CREATE TABLE fact2
(impressions	NUMERIC(3)	DEFAULT 1	NOT NULL, 
device_id	NUMERIC(3)		NOT NULL, 
avg_pos	NUMERIC	DEFAULT 0.0	NOT NULL, 
start_time	NUMERIC		NOT NULL, 
min_col	NUMERIC		NULL, 
column2_id	NUMERIC		NOT NULL, 
target_page_url	VARCHAR		NOT NULL, 
spend	NUMERIC	DEFAULT 0.0	NOT NULL, 
landing_page_url	VARCHAR		NOT NULL, 
network_type	VARCHAR(100)		NOT NULL, 
stats_date	DATE		NOT NULL, 
pricing_type	NUMERIC(3)		NOT NULL, 
max_col	NUMERIC		NULL, 
avg_col	NUMERIC		NULL, 
ad_group_id	NUMERIC		NOT NULL, 
count_col	NUMERIC		NULL, 
stats_source	NUMERIC(3)		NOT NULL, 
advertiser_id	NUMERIC		NOT NULL, 
max_bid	NUMERIC	DEFAULT 0.0	NOT NULL, 
average_cpc	NUMERIC		NULL, 
clicks	NUMERIC(3)	DEFAULT 0	NOT NULL, 
ad_format_id	NUMERIC(3)		NOT NULL, 
ctr	NUMERIC		NULL, 
campaign_id	NUMERIC		NOT NULL, 
keyword_id	NUMERIC		NOT NULL, 
column_id	NUMERIC		NOT NULL)
;

     
