// automatically generated by the FlatBuffers compiler, do not modify

package com.yahoo.maha.maha_druid_lookups.server.lookup.namespace.schema.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ProductAd extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static ProductAd getRootAsProductAd(ByteBuffer _bb) { return getRootAsProductAd(_bb, new ProductAd()); }
  public static ProductAd getRootAsProductAd(ByteBuffer _bb, ProductAd obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ProductAd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String description() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String status() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer statusAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer statusInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String imageUrlHq() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageUrlHqAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer imageUrlHqInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String imageUrlLarge() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageUrlLargeAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer imageUrlLargeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String sourceId() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sourceIdAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer sourceIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String title() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String lastUpdated() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lastUpdatedAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer lastUpdatedInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }

  public static int createProductAd(FlatBufferBuilder builder,
      int idOffset,
      int descriptionOffset,
      int statusOffset,
      int image_url_hqOffset,
      int image_url_largeOffset,
      int source_idOffset,
      int titleOffset,
      int last_updatedOffset) {
    builder.startTable(8);
    ProductAd.addTitle(builder, titleOffset);
    ProductAd.addSourceId(builder, source_idOffset);
    ProductAd.addImageUrlLarge(builder, image_url_largeOffset);
    ProductAd.addImageUrlHq(builder, image_url_hqOffset);
    ProductAd.addStatus(builder, statusOffset);
    ProductAd.addDescription(builder, descriptionOffset);
    ProductAd.addId(builder, idOffset);
    ProductAd.addLastUpdated(builder, last_updatedOffset);
    return ProductAd.endProductAd(builder);
  }

  public static void startProductAd(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(1, descriptionOffset, 0); }
  public static void addStatus(FlatBufferBuilder builder, int statusOffset) { builder.addOffset(2, statusOffset, 0); }
  public static void addImageUrlHq(FlatBufferBuilder builder, int imageUrlHqOffset) { builder.addOffset(3, imageUrlHqOffset, 0); }
  public static void addImageUrlLarge(FlatBufferBuilder builder, int imageUrlLargeOffset) { builder.addOffset(4, imageUrlLargeOffset, 0); }
  public static void addSourceId(FlatBufferBuilder builder, int sourceIdOffset) { builder.addOffset(5, sourceIdOffset, 0); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(6, titleOffset, 0); }
  public static void addLastUpdated(FlatBufferBuilder builder, int lastUpdatedOffset) { builder.addOffset(7, lastUpdatedOffset, 0); }
  public static int endProductAd(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishProductAdBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedProductAdBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ProductAd get(int j) { return get(new ProductAd(), j); }
    public ProductAd get(ProductAd obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

